# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omgitworks < Formula
  desc "A lightweight CLI tool for discovering, organizing, and navigating git repositories"
  homepage "https://github.com/daileyo/omgitworks"
  version "3.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daileyo/omgitworks/releases/download/v3.3.0/omgitworks_3.3.0_darwin_amd64.tar.gz"
      sha256 "0987b53b3b6dad877fb1d8995cc7bf8b511bcc77a84ce95e668ec296683b0169"

      define_method(:install) do
        bin.install "omgitworks"
        generate_completions_from_executable(bin/"omgitworks", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daileyo/omgitworks/releases/download/v3.3.0/omgitworks_3.3.0_darwin_arm64.tar.gz"
      sha256 "4e42cabafb9f2ca44e23f40e5d4fe30db74815fa21cdc9e71e102414df36cd01"

      define_method(:install) do
        bin.install "omgitworks"
        generate_completions_from_executable(bin/"omgitworks", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daileyo/omgitworks/releases/download/v3.3.0/omgitworks_3.3.0_linux_amd64.tar.gz"
      sha256 "27d5dd9beddb23232aec8956f37a1a39c9287baf2eeb2911eab259405fbd50f1"
      define_method(:install) do
        bin.install "omgitworks"
        generate_completions_from_executable(bin/"omgitworks", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daileyo/omgitworks/releases/download/v3.3.0/omgitworks_3.3.0_linux_arm64.tar.gz"
      sha256 "a1804b60e0141b8629400ad6472cefdc4d43b1b858499cd8052776eddd20f4c0"
      define_method(:install) do
        bin.install "omgitworks"
        generate_completions_from_executable(bin/"omgitworks", "completion")
      end
    end
  end

  test do
    system "#{bin}/omgitworks", "--version"
  end
end
