# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omgitworks < Formula
  desc "A lightweight CLI tool for discovering, organizing, and navigating git repositories"
  homepage "https://github.com/daileyo/omgitworks"
  version "3.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daileyo/omgitworks/releases/download/v3.0.4/omgitworks_3.0.4_darwin_amd64.tar.gz"
      sha256 "66530e735abbb0df77ddd28cf75b68b4643771b0fb59d606e62e78469fd1bd4c"

      define_method(:install) do
        bin.install "omgitworks"
        generate_completions_from_executable(bin/"omgitworks", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daileyo/omgitworks/releases/download/v3.0.4/omgitworks_3.0.4_darwin_arm64.tar.gz"
      sha256 "2954751887c662aabdcc21695bb716027dd141dea43dffee41b5dbe341342621"

      define_method(:install) do
        bin.install "omgitworks"
        generate_completions_from_executable(bin/"omgitworks", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daileyo/omgitworks/releases/download/v3.0.4/omgitworks_3.0.4_linux_amd64.tar.gz"
      sha256 "a4bf86ce147028fa3936da53ec6ebc288f5bad8f60a82431737d594d2a559ab0"
      define_method(:install) do
        bin.install "omgitworks"
        generate_completions_from_executable(bin/"omgitworks", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daileyo/omgitworks/releases/download/v3.0.4/omgitworks_3.0.4_linux_arm64.tar.gz"
      sha256 "cb4a98a6dab5e0b7d6e5ce8c4fc531904827c5663baa2c0b7329425f84496ae9"
      define_method(:install) do
        bin.install "omgitworks"
        generate_completions_from_executable(bin/"omgitworks", "completion")
      end
    end
  end

  test do
    system "#{bin}/omgitworks", "--version"
  end
end
